# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/anthony/Documents/fpga-phantom-circuits/src/code_4TDCs_receiver/ip/xc7a200tfbg676/project_ip_temporal/project_ip_temporal.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
# IP: The module: 'clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/anthony/Documents/fpga-phantom-circuits/src/code_4TDCs_receiver/ip/xc7a200tfbg676/project_ip_temporal/project_ip_temporal.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/anthony/Documents/fpga-phantom-circuits/src/code_4TDCs_receiver/ip/xc7a200tfbg676/project_ip_temporal/project_ip_temporal.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/anthony/Documents/fpga-phantom-circuits/src/code_4TDCs_receiver/ip/xc7a200tfbg676/project_ip_temporal/project_ip_temporal.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/anthony/Documents/fpga-phantom-circuits/src/code_4TDCs_receiver/ip/xc7a200tfbg676/project_ip_temporal/project_ip_temporal.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
# IP: The module: 'clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/anthony/Documents/fpga-phantom-circuits/src/code_4TDCs_receiver/ip/xc7a200tfbg676/project_ip_temporal/project_ip_temporal.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/anthony/Documents/fpga-phantom-circuits/src/code_4TDCs_receiver/ip/xc7a200tfbg676/project_ip_temporal/project_ip_temporal.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/anthony/Documents/fpga-phantom-circuits/src/code_4TDCs_receiver/ip/xc7a200tfbg676/project_ip_temporal/project_ip_temporal.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
