
set partname [lindex $argv 0]
set topDir [lindex $argv 1]

set IPGeneratorName "clk_wiz_ro_clock"
set projectName "project_ip_temporal"
append proDir $topDir $projectName "/"
append ipDir $proDir $projectName ".srcs/sources_1/ip/" $IPGeneratorName "/"
append XciFile $ipDir $IPGeneratorName ".xci"
append runsName $IPGeneratorName "_synth_1"

exec rm -rf $proDir

create_project $projectName $proDir -part $partname
create_ip -name clk_wiz -vendor xilinx.com -library ip -module_name $IPGeneratorName


# set_property -dict [list CONFIG.PRIM_IN_FREQ {200.000} CONFIG.CLKOUT2_USED {true} CONFIG.CLK_OUT1_PORT {clk_out_400} CONFIG.CLK_OUT2_PORT {clk_out_100} CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {400.000} CONFIG.CLKIN1_JITTER_PS {50.0} CONFIG.MMCM_CLKFBOUT_MULT_F {5.000} CONFIG.MMCM_CLKIN1_PERIOD {5.000} CONFIG.MMCM_CLKIN2_PERIOD {10.0} CONFIG.MMCM_CLKOUT0_DIVIDE_F {2.500} CONFIG.MMCM_CLKOUT1_DIVIDE {10} CONFIG.NUM_OUT_CLKS {2} CONFIG.CLKOUT1_JITTER {85.815} CONFIG.CLKOUT1_PHASE_ERROR {89.971} CONFIG.CLKOUT2_JITTER {112.316} CONFIG.CLKOUT2_PHASE_ERROR {89.971}] [get_ips $IPGeneratorName]
# set_property -dict [list CONFIG.CLKOUT2_USED {true} CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {200.000} CONFIG.CLKOUT2_REQUESTED_OUT_FREQ {170} CONFIG.MMCM_CLKFBOUT_MULT_F {8.500} CONFIG.MMCM_CLKOUT0_DIVIDE_F {4.250} CONFIG.MMCM_CLKOUT1_DIVIDE {5} CONFIG.NUM_OUT_CLKS {2} CONFIG.CLKOUT1_JITTER {121.717} CONFIG.CLKOUT1_PHASE_ERROR {109.126} CONFIG.CLKOUT2_JITTER {125.465} CONFIG.CLKOUT2_PHASE_ERROR {109.126}] [get_ips $IPGeneratorName]
#set_property -dict [list CONFIG.ENABLE_CLOCK_MONITOR {false} CONFIG.PRIM_IN_FREQ {165} CONFIG.CLKOUT2_USED {false} CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {200} CONFIG.PRIMITIVE {MMCM} CONFIG.CLKIN1_JITTER_PS {60.599999999999994} CONFIG.MMCM_DIVCLK_DIVIDE {11} CONFIG.MMCM_CLKFBOUT_MULT_F {60.000} CONFIG.MMCM_CLKIN1_PERIOD {6.061} CONFIG.MMCM_CLKIN2_PERIOD {10.0} CONFIG.MMCM_CLKOUT0_DIVIDE_F {4.500} CONFIG.MMCM_CLKOUT1_DIVIDE {1} CONFIG.NUM_OUT_CLKS {1} CONFIG.CLKOUT1_JITTER {293.064} CONFIG.CLKOUT1_PHASE_ERROR {474.406} CONFIG.CLKOUT2_JITTER {130.958} CONFIG.CLKOUT2_PHASE_ERROR {98.575}] [get_ips $IPGeneratorName]
#set_property -dict [list CONFIG.ENABLE_CLOCK_MONITOR {false} CONFIG.USE_INCLK_SWITCHOVER {false} CONFIG.PRIM_IN_FREQ {165} CONFIG.CLKOUT2_USED {false} CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {200} CONFIG.USE_RESET {true} CONFIG.USE_INCLK_STOPPED {false} CONFIG.PRIMITIVE {MMCM} CONFIG.SECONDARY_SOURCE {Single_ended_clock_capable_pin} CONFIG.SECONDARY_IN_FREQ {110.001} CONFIG.CLKIN1_JITTER_PS {60.599999999999994} CONFIG.CLKIN2_JITTER_PS {90.89999999999999} CONFIG.MMCM_DIVCLK_DIVIDE {11} CONFIG.MMCM_CLKFBOUT_MULT_F {60.000} CONFIG.MMCM_CLKIN1_PERIOD {6.061} CONFIG.MMCM_CLKIN2_PERIOD {9.091} CONFIG.MMCM_CLKOUT0_DIVIDE_F {4.500} CONFIG.MMCM_CLKOUT1_DIVIDE {1} CONFIG.NUM_OUT_CLKS {1} CONFIG.CLKOUT1_JITTER {293.064} CONFIG.CLKOUT1_PHASE_ERROR {474.406} CONFIG.CLKOUT2_JITTER {322.370} CONFIG.CLKOUT2_PHASE_ERROR {474.406}] [get_ips $IPGeneratorName]

#set_property -dict [list CONFIG.JITTER_SEL {Min_O_Jitter} CONFIG.PRIM_IN_FREQ {420} CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {200} CONFIG.USE_LOCKED {true} CONFIG.CLKIN1_JITTER_PS {60.599999999999994} CONFIG.MMCM_DIVCLK_DIVIDE {11} CONFIG.MMCM_CLKFBOUT_MULT_F {60.000} CONFIG.MMCM_CLKIN1_PERIOD {6.061} CONFIG.MMCM_CLKIN2_PERIOD {10.0} CONFIG.MMCM_CLKOUT0_DIVIDE_F {4.500} CONFIG.CLKOUT1_JITTER {293.064} CONFIG.CLKOUT1_PHASE_ERROR {474.406}] [get_ips $IPGeneratorName]

# set_property -dict [list CONFIG.JITTER_SEL {Min_O_Jitter} CONFIG.PRIM_IN_FREQ {440} CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {200} CONFIG.USE_LOCKED {true} CONFIG.CLKIN1_JITTER_PS {23.799999999999997} CONFIG.MMCM_DIVCLK_DIVIDE {3} CONFIG.MMCM_BANDWIDTH {HIGH} CONFIG.MMCM_CLKFBOUT_MULT_F {10.000} CONFIG.MMCM_CLKIN1_PERIOD {2.381} CONFIG.MMCM_CLKIN2_PERIOD {10.0} CONFIG.MMCM_CLKOUT0_DIVIDE_F {7.000} CONFIG.CLKOUT1_JITTER {88.076} CONFIG.CLKOUT1_PHASE_ERROR {77.206}] [get_ips $IPGeneratorName]
# set_property -dict [list CONFIG.JITTER_SEL {Max_I_Jitter} CONFIG.PRIM_IN_FREQ {410} CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {200} CONFIG.USE_LOCKED {true} CONFIG.CLKIN1_JITTER_PS {24.39} CONFIG.MMCM_DIVCLK_DIVIDE {1} CONFIG.MMCM_BANDWIDTH {LOW} CONFIG.MMCM_CLKFBOUT_MULT_F {2.500} CONFIG.MMCM_CLKIN1_PERIOD {2.439} CONFIG.MMCM_CLKIN2_PERIOD {10.0} CONFIG.MMCM_CLKOUT0_DIVIDE_F {5.125} CONFIG.CLKOUT1_JITTER {86.808} CONFIG.CLKOUT1_PHASE_ERROR {166.651}] [get_ips $IPGeneratorName]
# set_property -dict [list CONFIG.USE_PHASE_ALIGNMENT {true} CONFIG.JITTER_SEL {Min_O_Jitter} CONFIG.PRIM_IN_FREQ {470} CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {200} CONFIG.USE_SAFE_CLOCK_STARTUP {true} CONFIG.SECONDARY_SOURCE {Single_ended_clock_capable_pin} CONFIG.CLKIN1_JITTER_PS {22.72} CONFIG.CLKOUT1_DRIVES {BUFGCE} CONFIG.CLKOUT2_DRIVES {BUFGCE} CONFIG.CLKOUT3_DRIVES {BUFGCE} CONFIG.CLKOUT4_DRIVES {BUFGCE} CONFIG.CLKOUT5_DRIVES {BUFGCE} CONFIG.CLKOUT6_DRIVES {BUFGCE} CONFIG.CLKOUT7_DRIVES {BUFGCE} CONFIG.FEEDBACK_SOURCE {FDBK_AUTO} CONFIG.MMCM_BANDWIDTH {HIGH} CONFIG.MMCM_CLKFBOUT_MULT_F {3.125} CONFIG.MMCM_CLKIN1_PERIOD {2.273} CONFIG.MMCM_CLKIN2_PERIOD {10.0} CONFIG.MMCM_CLKOUT0_DIVIDE_F {6.875} CONFIG.CLKOUT1_JITTER {83.047} CONFIG.CLKOUT1_PHASE_ERROR {68.615}] [get_ips $IPGeneratorName]

# set_property -dict [list CONFIG.USE_PHASE_ALIGNMENT {false} CONFIG.JITTER_SEL {Min_O_Jitter} CONFIG.PRIM_IN_FREQ {577} CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {200} CONFIG.USE_SAFE_CLOCK_STARTUP {true} CONFIG.SECONDARY_SOURCE {Single_ended_clock_capable_pin} CONFIG.CLKIN1_JITTER_PS {21.269999999999996} CONFIG.CLKOUT1_DRIVES {BUFGCE} CONFIG.CLKOUT2_DRIVES {BUFGCE} CONFIG.CLKOUT3_DRIVES {BUFGCE} CONFIG.CLKOUT4_DRIVES {BUFGCE} CONFIG.CLKOUT5_DRIVES {BUFGCE} CONFIG.CLKOUT6_DRIVES {BUFGCE} CONFIG.CLKOUT7_DRIVES {BUFGCE} CONFIG.FEEDBACK_SOURCE {FDBK_AUTO} CONFIG.MMCM_BANDWIDTH {HIGH} CONFIG.MMCM_CLKFBOUT_MULT_F {2.500} CONFIG.MMCM_CLKIN1_PERIOD {2.128} CONFIG.MMCM_CLKIN2_PERIOD {10.0} CONFIG.MMCM_CLKOUT0_DIVIDE_F {5.875} CONFIG.CLKOUT1_JITTER {85.155} CONFIG.CLKOUT1_PHASE_ERROR {73.805}] [get_ips $IPGeneratorName]
# set_property -dict [list CONFIG.USE_PHASE_ALIGNMENT {false} CONFIG.JITTER_SEL {Max_I_Jitter} CONFIG.PRIM_IN_FREQ {470} CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {200} CONFIG.USE_SAFE_CLOCK_STARTUP {true} CONFIG.SECONDARY_SOURCE {Single_ended_clock_capable_pin} CONFIG.CLKIN1_JITTER_PS {21.269999999999996} CONFIG.CLKOUT1_DRIVES {BUFGCE} CONFIG.CLKOUT2_DRIVES {BUFGCE} CONFIG.CLKOUT3_DRIVES {BUFGCE} CONFIG.CLKOUT4_DRIVES {BUFGCE} CONFIG.CLKOUT5_DRIVES {BUFGCE} CONFIG.CLKOUT6_DRIVES {BUFGCE} CONFIG.CLKOUT7_DRIVES {BUFGCE} CONFIG.FEEDBACK_SOURCE {FDBK_AUTO} CONFIG.MMCM_BANDWIDTH {LOW} CONFIG.MMCM_CLKFBOUT_MULT_F {2.500} CONFIG.MMCM_CLKIN1_PERIOD {2.128} CONFIG.MMCM_CLKIN2_PERIOD {10.0} CONFIG.MMCM_CLKOUT0_DIVIDE_F {5.875} CONFIG.CLKOUT1_JITTER {85.068} CONFIG.CLKOUT1_PHASE_ERROR {142.747}] [get_ips $IPGeneratorName]
set_property -dict [list CONFIG.USE_PHASE_ALIGNMENT {false} CONFIG.PRIM_IN_FREQ {586} CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {200} CONFIG.USE_SAFE_CLOCK_STARTUP {true} CONFIG.SECONDARY_SOURCE {Single_ended_clock_capable_pin} CONFIG.CLKIN1_JITTER_PS {21.269999999999996} CONFIG.CLKOUT1_DRIVES {BUFGCE} CONFIG.CLKOUT2_DRIVES {BUFGCE} CONFIG.CLKOUT3_DRIVES {BUFGCE} CONFIG.CLKOUT4_DRIVES {BUFGCE} CONFIG.CLKOUT5_DRIVES {BUFGCE} CONFIG.CLKOUT6_DRIVES {BUFGCE} CONFIG.CLKOUT7_DRIVES {BUFGCE} CONFIG.FEEDBACK_SOURCE {FDBK_AUTO} CONFIG.MMCM_CLKFBOUT_MULT_F {2.500} CONFIG.MMCM_CLKIN1_PERIOD {2.128} CONFIG.MMCM_CLKIN2_PERIOD {10.0} CONFIG.MMCM_CLKOUT0_DIVIDE_F {5.875} CONFIG.CLKOUT1_JITTER {85.155} CONFIG.CLKOUT1_PHASE_ERROR {73.805}] [get_ips $IPGeneratorName]

generate_target {instantiation_template} [get_files $XciFile]
update_compile_order -fileset sources_1
generate_target all [get_files  $XciFile]
catch { config_ip_cache -export [get_ips -all $IPGeneratorName] }
export_ip_user_files -of_objects [get_files $XciFile] -no_script -sync -force 
create_ip_run [get_files -of_objects [get_fileset sources_1] $XciFile]
launch_runs -jobs 16 $runsName

exec cp -rf $ipDir $topDir
exec rm -rf $proDir

