
set partname [lindex $argv 0]
set topDir [lindex $argv 1]

set IPGeneratorName "clk_wiz_0"
set projectName "project_ip_temporal"
append proDir $topDir $projectName "/"
append ipDir $proDir $projectName ".srcs/sources_1/ip/" $IPGeneratorName "/"
puts $topDir$IPGeneratorName
append XciFile $ipDir $IPGeneratorName ".xci"
append runsName $IPGeneratorName "_synth_1"

exec rm -rf $proDir
exec rm -rf $topDir$IPGeneratorName/*

create_project $projectName $proDir -part $partname
create_ip -name clk_wiz -vendor xilinx.com -library ip -version 6.0 -module_name $IPGeneratorName

# set_property -dict [list CONFIG.PRIM_IN_FREQ {200.000} CONFIG.CLKOUT2_USED {true} CONFIG.CLKOUT3_USED {true} CONFIG.CLKOUT4_USED {true} CONFIG.CLKOUT5_USED {true} CONFIG.PRIMARY_PORT {clk_in} CONFIG.CLK_OUT1_PORT {clk_out_90} CONFIG.CLK_OUT2_PORT {clk_out_100} CONFIG.CLK_OUT3_PORT {clk_out_112} CONFIG.CLK_OUT4_PORT {clk_out_128} CONFIG.CLK_OUT5_PORT {clk_out_150} CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {90} CONFIG.CLKOUT3_REQUESTED_OUT_FREQ {112} CONFIG.CLKOUT4_REQUESTED_OUT_FREQ {128} CONFIG.CLKOUT5_REQUESTED_OUT_FREQ {150} CONFIG.CLKIN1_JITTER_PS {50.0} CONFIG.MMCM_DIVCLK_DIVIDE {1} CONFIG.MMCM_CLKFBOUT_MULT_F {4.500} CONFIG.MMCM_CLKIN1_PERIOD {5.000} CONFIG.MMCM_CLKIN2_PERIOD {10.0} CONFIG.MMCM_CLKOUT0_DIVIDE_F {10.000} CONFIG.MMCM_CLKOUT1_DIVIDE {9} CONFIG.MMCM_CLKOUT2_DIVIDE {8} CONFIG.MMCM_CLKOUT3_DIVIDE {7} CONFIG.MMCM_CLKOUT4_DIVIDE {6} CONFIG.NUM_OUT_CLKS {5} CONFIG.CLKOUT1_JITTER {113.004} CONFIG.CLKOUT1_PHASE_ERROR {91.235} CONFIG.CLKOUT2_JITTER {110.629} CONFIG.CLKOUT2_PHASE_ERROR {91.235} CONFIG.CLKOUT3_JITTER {108.109} CONFIG.CLKOUT3_PHASE_ERROR {91.235} CONFIG.CLKOUT4_JITTER {105.328} CONFIG.CLKOUT4_PHASE_ERROR {91.235} CONFIG.CLKOUT5_JITTER {102.207} CONFIG.CLKOUT5_PHASE_ERROR {91.235}] [get_ips $IPGeneratorName]
# set_property -dict [list CONFIG.PRIM_IN_FREQ {200.000} CONFIG.CLKOUT2_USED {true} CONFIG.CLKOUT3_USED {true} CONFIG.CLKOUT4_USED {false} CONFIG.PRIMARY_PORT {clk_in} CONFIG.CLK_OUT1_PORT {clk_out_20} CONFIG.CLK_OUT2_PORT {clk_out_50} CONFIG.CLK_OUT3_PORT {clk_out_100} CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {20} CONFIG.CLKOUT2_REQUESTED_OUT_FREQ {50} CONFIG.CLKIN1_JITTER_PS {50.0} CONFIG.MMCM_CLKFBOUT_MULT_F {5.000} CONFIG.MMCM_CLKIN1_PERIOD {5.000} CONFIG.MMCM_CLKIN2_PERIOD {10.0} CONFIG.MMCM_CLKOUT0_DIVIDE_F {50.000} CONFIG.MMCM_CLKOUT1_DIVIDE {20} CONFIG.MMCM_CLKOUT2_DIVIDE {10} CONFIG.MMCM_CLKOUT3_DIVIDE {1} CONFIG.NUM_OUT_CLKS {3} CONFIG.CLKOUT1_JITTER {155.330} CONFIG.CLKOUT1_PHASE_ERROR {89.971} CONFIG.CLKOUT2_JITTER {129.198} CONFIG.CLKOUT2_PHASE_ERROR {89.971} CONFIG.CLKOUT3_JITTER {112.316} CONFIG.CLKOUT3_PHASE_ERROR {89.971} CONFIG.CLKOUT4_JITTER {112.316} CONFIG.CLKOUT4_PHASE_ERROR {89.971}] [get_ips $IPGeneratorName]
set_property -dict [list CONFIG.CLKOUT1_USED {true} CONFIG.PRIM_IN_FREQ {200.000} CONFIG.CLKOUT2_USED {true} CONFIG.CLKOUT3_USED {true} CONFIG.CLKOUT4_USED {true} CONFIG.CLKOUT5_USED {true} CONFIG.PRIMARY_PORT {clk_in} CONFIG.CLK_OUT1_PORT {clk_out_20} CONFIG.CLK_OUT2_PORT {clk_out_30} CONFIG.CLK_OUT3_PORT {clk_out_40} CONFIG.CLK_OUT4_PORT {clk_out_50} CONFIG.CLK_OUT5_PORT {clk_out_60} CONFIG.CLK_OUT6_PORT {clk_out_60} CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {20} CONFIG.CLKOUT2_REQUESTED_OUT_FREQ {30} CONFIG.CLKOUT3_REQUESTED_OUT_FREQ {40} CONFIG.CLKOUT4_REQUESTED_OUT_FREQ {50} CONFIG.CLKOUT5_REQUESTED_OUT_FREQ {60} CONFIG.CLKOUT6_REQUESTED_OUT_FREQ {60} CONFIG.CLKIN1_JITTER_PS {50.0} CONFIG.CLKOUT6_USED {false} CONFIG.MMCM_DIVCLK_DIVIDE {1} CONFIG.MMCM_CLKFBOUT_MULT_F {6.000} CONFIG.MMCM_CLKIN1_PERIOD {5.000} CONFIG.MMCM_CLKIN2_PERIOD {10.0} CONFIG.MMCM_CLKOUT0_DIVIDE_F {60.000} CONFIG.MMCM_CLKOUT1_DIVIDE {40} CONFIG.MMCM_CLKOUT2_DIVIDE {30} CONFIG.MMCM_CLKOUT3_DIVIDE {24} CONFIG.MMCM_CLKOUT4_DIVIDE {20} CONFIG.MMCM_CLKOUT5_DIVIDE {1} CONFIG.NUM_OUT_CLKS {5} CONFIG.CLKOUT1_JITTER {146.346} CONFIG.CLKOUT1_PHASE_ERROR {82.655} CONFIG.CLKOUT2_JITTER {134.641} CONFIG.CLKOUT2_PHASE_ERROR {82.655} CONFIG.CLKOUT3_JITTER {127.032} CONFIG.CLKOUT3_PHASE_ERROR {82.655} CONFIG.CLKOUT4_JITTER {121.478} CONFIG.CLKOUT4_PHASE_ERROR {82.655} CONFIG.CLKOUT5_JITTER {117.146} CONFIG.CLKOUT5_PHASE_ERROR {82.655} CONFIG.CLKOUT6_JITTER {109.203} CONFIG.CLKOUT6_PHASE_ERROR {77.998}] [get_ips $IPGeneratorName]


generate_target {instantiation_template} [get_files $XciFile]
generate_target all [get_files  $XciFile]
catch { config_ip_cache -export [get_ips -all $IPGeneratorName] }

export_ip_user_files -of_objects [get_files $XciFile] -no_script -sync -force 

create_ip_run [get_files -of_objects [get_fileset sources_1] $XciFile]
launch_runs -jobs 16 $runsName



exec cp -rf $ipDir $topDir
# Do not remove the project folder
# exec rm -rf $proDir

